apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
  namespace: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: madhubabu89/wisecow:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 4499